### PR TITLE
Use print as function

### PR DESCRIPTION
**Pull request by elyezer**
First move in order to support both Python 2.7+ and 3+

### CODE REVIEW

**Comment by sthirugn** [comment]
@elyezer ty, can you also paste some test results using https://github.com/SatelliteQE/testimony/blob/master/tests/test_sample.py just to make sure that everything still works.

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
ACK pending comment

**Comment by elyezer** [comment]
Sample output

```
for i in print summary validate_docstring bugs manual auto tags; do testimony $i ../robottelo/tests/foreman/api/test_rhsm.py; done
../robottelo/tests/foreman/api/test_rhsm.py
===========================================

TC 1
Test: Check whether the path exists.
Feature: Red Hat Subscription Manager
Assert: Issuing an HTTP GET produces an HTTP 200 response with an
``application/json`` content-type, and the response is a list.
This test targets bugzilla bug 1112802.

Total Number of test cases:      1
Total Number of automated cases: 1 (100%)
Total Number of manual cases:    0 (0%)
Test cases with no docstrings:   0 (0%)
Total Number of invalid docstrings:  0/1 (0.00%)
Test cases with no docstrings:   0/1 (0.00%) 
Test cases missing minimal docstrings:  0/1 (0.00%)
Test cases with invalid tags 0/1 (0.00%)

Total Number of test cases affected by bugs: 0/1 (0.00%)
../robottelo/tests/foreman/api/test_rhsm.py
===========================================

No manual test cases found.

../robottelo/tests/foreman/api/test_rhsm.py
===========================================

TC 1
Test: Check whether the path exists.
Feature: Red Hat Subscription Manager
Assert: Issuing an HTTP GET produces an HTTP 200 response with an
``application/json`` content-type, and the response is a list.
This test targets bugzilla bug 1112802.

Input tags required for this report.  See testimony --help
```

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
