### PR TITLE
Add support for markdown output

### PR DESCRIPTION
**Pull request by dosas**

### CODE REVIEW

**Comment by dosas** [comment]
@elyezer ping

**Comment by JacobCallahan** [comment]
Hi there! Can you add a comment in here showing an example of the output?

**Comment by dosas** [comment]
Sure:

```
testimony print -m robottelo/tests/foreman/cli/

# robottelo/tests/foreman/cli/test_syncplan.py


## test_positive_create_with_name:119


### test

Check if syncplan can be created with random names


### invalid tokens
* requirement: Syncplan
* caseautomation: Automated
* casecomponent: SyncPlans
* team: Phoenix-content
* caseimportance: Critical
* id: dc0a86f7-4219-427e-92fd-29352dbdbfce
* parametrized: yes
* expectedresults: Sync plan is created and has random name




## test_positive_create_with_description:139


### test

Check if syncplan can be created with random description


### invalid tokens
* requirement: Syncplan
* caseautomation: Automated
* casecomponent: SyncPlans
* team: Phoenix-content
* caseimportance: Critical
* id: a1bbe81b-60f5-4a19-b400-a02a23fa1dfa
* parametrized: yes
* expectedresults: Sync plan is created and has random description




## test_positive_create_with_interval:159


### test

Check if syncplan can be created with varied intervals


### invalid tokens
* requirement: Syncplan
* caseautomation: Automated
* casecomponent: SyncPlans
* team: Phoenix-content
* caseimportance: Critical
* id: 32eb0c1d-0c9a-4fb5-a185-68d0d705fbce
* parametrized: yes
* expectedresults: Sync plan is created and has selected interval

```

**Review by ogajduse — APPROVED** [review]
The code would need some formatting, but that is something that the ruff formatted or black can take care of. We can set it up in a different PR.
LGTM

**Review by JacobCallahan — APPROVED** [review]

**Comment by ogajduse** [comment]
https://github.com/SatelliteQE/testimony/releases/tag/2.4.0 is out and available on PyPi. Thank you for your contribution.

**Pull request merged**
