### PR TITLE
Improve get_docstrings function

### LINKED ISSUE #17: testimony assumes case(s) inside a class
If user has a bunch of test stubs in a file that are not contained within a class, no parsing is performed on the list.

This may or may not be problematic - I can see a use case where someone has written up a bunch of test stubs and just wants to parse them for validity before adding them to the code/attach them for automation in a github ticket.

We should determine if this is a valid use case or not.  

* If not, we need to indicate in the README that stubs must exist within a class to be parsed
* If so, we need to tweak the heuristic to allow stubs outside a class.

### PR DESCRIPTION
**Pull request by elyezer**
Take advantage of ast.walk to walk into the ast tree and grab all
functions node even if they are not inside a TestCase class. All
functions that name starts with "test_" will be considered as being a
test function or method and the docstring will be checked.

This also reduces the complexity of the function since we have reduced
the number of for loops and some indentation level.

We can close #17 when this is merged since it will grab all functions or methods that starts with 'test_'.

### CODE REVIEW

**Comment by omaciel** [comment]
@elyezer can you add a sample output (before and after the PR)?

**Comment by elyezer** [comment]
@omaciel the output have not changed, using the sample test module from testimony:

Before:

```
$ testimony summary tests 

Fetching Test Path tests


Fetching Test Path tests/__pycache__

Total Number of test cases:      7
Total Number of automated cases: 4 (57%)
Total Number of manual cases:    3 (43%)
Test cases with no docstrings:   1
```

After:

```
$ testimony summary tests

Fetching Test Path tests


Fetching Test Path tests/__pycache__

Total Number of test cases:      7
Total Number of automated cases: 4 (57%)
Total Number of manual cases:    3 (43%)
Test cases with no docstrings:   1
```

**Comment by omaciel** [comment]
@elyezer mea culpa, I guess what I really want to know is, what exactly has been improved? You said:

> Take advantage of ast.walk and make sure to grab all test methods even if the module has multiple TestCase classes.

So what exactly was happening that you are now fixing?

**Comment by elyezer** [comment]
@omaciel the main goal of this PR is to improve how is grab the test functions. Using ast.walk will walk into the ast tree returning all nodes starting on the main node which is a test module. This way we don't have to use many for loops.

About grabbing all testcases classes @sthirugn told me that sometimes testimony was not getting all test methods and by using the new approach that will not happen and also will grab all test functions that is not inside a testcase class.

**Comment by omaciel** [comment]
@elyezer thank you, it all makes sense now :)

**Comment by elyezer** [comment]
@omaciel I have updated the commit message and the PR description now it should be more clear. Thanks for asking and make me be more explicit and describe it better.

**Comment by Ichimonji10** [comment]
I think @omaciel has asked all the right questions. ACK

**Comment by omaciel** [comment]
ACK

@elyezer do we have a test for report generating?

**Comment by elyezer** [comment]
@omaciel not yet.

**Comment by sthirugn** [comment]
:+1:

**Pull request merged**
